import type { Library, MaterialItem, Profile } from '@/types/saunaMaterials';

// ───────────────────────────────────────────────────────────────────────────
// Original seeds — kept intact so existing project files (Slow Folk demo,
// fixtures, tests) keep resolving by ID.
// ───────────────────────────────────────────────────────────────────────────

const ORIGINAL_PROFILES: Profile[] = [
  {
    id: 'thermo-aspen-92-tg',
    name: 'Thermo Aspen 92mm T&G',
    category: 'wallCladding',
    species: 'Thermo aspen',
    faceWidth: 92,
    coverWidth: 84,
    thickness: 15,
    stockLengths: [1.8, 2.4, 3.0],
    pricePerLM: null,
    supplier: 'Modinex',
    notes: '',
  },
  {
    id: 'thermo-aspen-116-tg',
    name: 'Thermo Aspen 116mm T&G',
    category: 'wallCladding',
    species: 'Thermo aspen',
    faceWidth: 116,
    coverWidth: 108,
    thickness: 15,
    stockLengths: [1.8, 2.4, 3.0],
    pricePerLM: null,
    supplier: 'Modinex',
    notes: '',
  },
  {
    id: 'thermo-spruce-92-tg',
    name: 'Thermo Spruce 92mm T&G',
    category: 'wallCladding',
    species: 'Thermo spruce',
    faceWidth: 92,
    coverWidth: 84,
    thickness: 15,
    stockLengths: [1.8, 2.4, 3.0],
    pricePerLM: null,
    supplier: 'Modinex',
    notes: '',
  },
  {
    id: 'abachi-90-slat',
    name: 'Abachi 90mm slat',
    category: 'benchSlat',
    species: 'Abachi',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 28,
    stockLengths: [1.8, 2.4],
    pricePerLM: null,
    supplier: 'Modinex',
    notes: '',
  },
  {
    id: 'thermo-aspen-90-slat',
    name: 'Thermo Aspen 90mm slat',
    category: 'benchSlat',
    species: 'Thermo aspen',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 32,
    stockLengths: [1.8, 2.4, 3.0],
    pricePerLM: null,
    supplier: 'Modinex',
    notes: '',
  },
  {
    id: 'pine-42x42-framing',
    name: '42×42 framing',
    category: 'framing',
    species: 'Pine MGP10',
    faceWidth: 42,
    coverWidth: 42,
    thickness: 42,
    stockLengths: [2.4, 3.0, 3.6],
    pricePerLM: null,
    supplier: 'Local timber yard',
    notes: '',
  },
  {
    id: 'pine-22x42-batten',
    name: '22×42 batten',
    category: 'batten',
    species: 'Pine',
    faceWidth: 42,
    coverWidth: 42,
    thickness: 22,
    stockLengths: [2.4, 3.0],
    pricePerLM: null,
    supplier: 'Local timber yard',
    notes: '',
  },
  {
    id: 'thermo-aspen-backrest',
    name: 'Thermo Aspen backrest profile',
    category: 'backrest',
    species: 'Thermo aspen',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 28,
    stockLengths: [1.8, 2.4],
    pricePerLM: null,
    supplier: 'Modinex',
    notes: '',
  },
];

// ───────────────────────────────────────────────────────────────────────────
// SDS Australia — quote Q-003752 (April 2026, Slow Folk Brunswick)
// Prices listed below are inc-GST (rate × 1.10).
// ───────────────────────────────────────────────────────────────────────────

const SDS_AUSTRALIA_PROFILES: Profile[] = [
  {
    id: 'sds-alder-ht-90x15-tg',
    name: 'Premium European Alder Heat-Treated 90×15mm T&G',
    category: 'wallCladding',
    species: 'European alder, heat treated',
    faceWidth: 90,
    coverWidth: 84,
    thickness: 15,
    stockLengths: [2.4],
    pricePerLM: 26.84,
    supplier: 'SDS Australia',
    notes: 'SKU 4741409273812 · 4.6 pieces per m² · vertical wall + ceiling cladding',
  },
  {
    id: 'sds-alder-ht-90x21-slat',
    name: 'Premium European Alder Heat-Treated 90×21mm slat',
    category: 'benchSlat',
    species: 'European alder, heat treated',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 21,
    stockLengths: [2.4],
    pricePerLM: 38.17,
    supplier: 'SDS Australia',
    notes: 'SKU 4741409497416 · 4.7 pieces per m² · bench tops (will require a join)',
  },
  {
    id: 'sds-alder-ht-65x21-fascia',
    name: 'Premium European Alder Heat-Treated 65×21mm slat',
    category: 'backrest',
    species: 'European alder, heat treated',
    faceWidth: 65,
    coverWidth: 65,
    thickness: 21,
    stockLengths: [2.4],
    pricePerLM: 21.89,
    supplier: 'SDS Australia',
    notes: 'SKU HTALD65X21X2400 · 6.4 pieces per m² · backrest and fascia',
  },
  {
    id: 'sds-euro-framing-70x19-batten',
    name: 'Premium European Framing 70×19mm batten',
    category: 'batten',
    species: 'European softwood, raw',
    faceWidth: 70,
    coverWidth: 70,
    thickness: 19,
    stockLengths: [6.0],
    pricePerLM: 24.29,
    supplier: 'SDS Australia',
    notes: 'SKU PREURFT70196000 · battens between foil and cladding',
  },
  {
    id: 'sds-euro-framing-90x35',
    name: 'Premium European Framing 90×35mm',
    category: 'framing',
    species: 'European softwood, raw',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 35,
    stockLengths: [6.0],
    pricePerLM: 33.00,
    supplier: 'SDS Australia',
    notes: 'SKU PREURFTR90356000 · bench frame, legs and supports',
  },
];

// ───────────────────────────────────────────────────────────────────────────
// SDS Australia — Western Red Cedar product range
// (sdsaustralia.com/product-category/sauna-timber/, fetched April 2026).
// Prices inc-GST. Per-LM rates derived from confirmed per-m² × face-width or
// per-piece ÷ shortest-stock-length; left null on variants whose price is
// only revealed in the supplier's variation picker.
// ───────────────────────────────────────────────────────────────────────────

const SDS_CEDAR_LENGTHS = [1.8, 2.1, 2.4, 2.7, 3.0];
const SDS_PANELLING_LENGTHS = [1.8, 2.1, 2.4, 2.7, 3.0, 3.3, 3.6, 3.9, 4.0];
const SDS_TONGUE_MM = 6;

const SDS_CEDAR_PROFILES: Profile[] = [
  // Vee Joint Cladding
  {
    id: 'sds-cedar-vj-86x9',
    name: 'Premium WRC V-joint 86×9mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 86,
    coverWidth: 86 - SDS_TONGUE_MM,
    thickness: 9,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: 16.50,
    supplier: 'SDS Australia',
    notes: 'Grade A · vee joint · SKU WRVJ0860091800… · ~$191.86/m²',
  },
  {
    id: 'sds-cedar-vj-137x9',
    name: 'Premium WRC V-joint 137×9mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 137,
    coverWidth: 137 - SDS_TONGUE_MM,
    thickness: 9,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'Grade A · vee joint · SKU WRVJ137009… · request quote',
  },
  {
    id: 'sds-cedar-vj-78x18',
    name: 'Premium WRC V-joint 78×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 78,
    coverWidth: 78 - SDS_TONGUE_MM,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'Grade A · vee joint · SKU WRVJ0780181800… · request quote',
  },
  {
    id: 'sds-cedar-vj-127x18',
    name: 'Premium WRC V-joint 127×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 127,
    coverWidth: 127 - SDS_TONGUE_MM,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'Grade A · vee joint · request quote',
  },

  // Panelling (single profile, longer length range)
  {
    id: 'sds-cedar-panel-84x10',
    name: 'Premium WRC Sauna Panelling 84×10mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 84,
    coverWidth: 84 - SDS_TONGUE_MM,
    thickness: 10,
    stockLengths: SDS_PANELLING_LENGTHS,
    pricePerLM: 19.41,
    supplier: 'SDS Australia',
    notes: 'Grade A · sauna profile · SKU WRSP084010… · $231.02/m²',
  },

  // DAR Bench Board (multi-dimension)
  {
    id: 'sds-cedar-dar-65x17',
    name: 'Premium WRC DAR Bench Board 65×17mm',
    category: 'backrest',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 65,
    coverWidth: 65,
    thickness: 17,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: 20.87,
    supplier: 'SDS Australia',
    notes: 'DAR · backrest / fascia · supplier-stated $20.87/lm',
  },
  {
    id: 'sds-cedar-dar-90x17',
    name: 'Premium WRC DAR Bench Board 90×17mm',
    category: 'backrest',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 17,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'DAR · backrest · request quote',
  },
  {
    id: 'sds-cedar-dar-90x38',
    name: 'Premium WRC DAR Bench Board 90×38mm',
    category: 'benchSlat',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 38,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'DAR · classic 38mm bench top · request quote',
  },
  {
    id: 'sds-cedar-dar-140x12',
    name: 'Premium WRC DAR Bench Board 140×12mm',
    category: 'batten',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 140,
    coverWidth: 140,
    thickness: 12,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'DAR · wide thin board · request quote',
  },
  {
    id: 'sds-cedar-dar-190x17',
    name: 'Premium WRC DAR Bench Board 190×17mm',
    category: 'benchSlat',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 190,
    coverWidth: 190,
    thickness: 17,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'DAR · wide bench top · request quote',
  },

  // Shiplap Cladding
  {
    id: 'sds-cedar-ship-78x18',
    name: 'Premium WRC Shiplap 78×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 78,
    coverWidth: 78 - SDS_TONGUE_MM,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: 27.80,
    supplier: 'SDS Australia',
    notes: 'Grade A · shiplap · SKU WRSL078018… · $356.41/m²',
  },
  {
    id: 'sds-cedar-ship-127x18',
    name: 'Premium WRC Shiplap 127×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 127,
    coverWidth: 127 - SDS_TONGUE_MM,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'Grade A · shiplap · SKU WRSL127018… · request quote',
  },

  // Castellated Cladding (Decor 1/2/3 grooves are pricing variants of these)
  {
    id: 'sds-cedar-cast-78x18',
    name: 'Premium WRC Castellated 78×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 78,
    coverWidth: 78 - SDS_TONGUE_MM,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: 33.03,
    supplier: 'SDS Australia',
    notes: 'Grade A · castellated · Decor 1/2/3 grooves available · ~$363/m²',
  },
  {
    id: 'sds-cedar-cast-127x18',
    name: 'Premium WRC Castellated 127×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 127,
    coverWidth: 127 - SDS_TONGUE_MM,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'Grade A · castellated · Decor 3 (triple groove) · request quote',
  },
  {
    id: 'sds-cedar-cast-78x26',
    name: 'Premium WRC Castellated 78×26mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 78,
    coverWidth: 78 - SDS_TONGUE_MM,
    thickness: 26,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: null,
    supplier: 'SDS Australia',
    notes: 'Grade A · thick castellated · request quote',
  },

  // Rough Sawn Charred Look
  {
    id: 'sds-cedar-rscharred-120x18',
    name: 'Rough Sawn WRC Charred Look 120×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar (BC, Canada)',
    faceWidth: 120,
    coverWidth: 120,
    thickness: 18,
    stockLengths: SDS_CEDAR_LENGTHS,
    pricePerLM: 43.08,
    supplier: 'SDS Australia',
    notes: 'Charred look · butt-jointed · $359.03/m²',
  },
];

// ───────────────────────────────────────────────────────────────────────────
// Kosny — Sauna Timbers price list, April 2026
// All prices inc-GST per supplier header.
// Tongue allowance for T&G / shiplap / castellated profiles: 6mm.
// ───────────────────────────────────────────────────────────────────────────

const KOSNY_CEDAR_LENGTHS = [1.8, 2.1, 2.4, 2.7, 3.0];
const KOSNY_JAPANESE_LENGTHS = [1.8, 2.0, 2.8, 3.0, 3.8, 4.0];
const KOSNY_TONGUE_MM = 6;

const KOSNY_CEDAR_PROFILES: Profile[] = [
  // Vee Joint Cladding
  {
    id: 'kosny-cedar-vj-86x9',
    name: 'Western Red Cedar V-joint 86×9mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 9,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 16.50,
    supplier: 'Kosny',
    notes: 'Grade A · vee joint cladding',
  },
  {
    id: 'kosny-cedar-vj-137x9',
    name: 'Western Red Cedar V-joint 137×9mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 137,
    coverWidth: 137 - KOSNY_TONGUE_MM,
    thickness: 9,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 27.50,
    supplier: 'Kosny',
    notes: 'Grade A · vee joint cladding',
  },
  {
    id: 'kosny-cedar-vj-78x18',
    name: 'Western Red Cedar V-joint 78×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 78,
    coverWidth: 78 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 27.80,
    supplier: 'Kosny',
    notes: 'Grade A · vee joint cladding',
  },
  {
    id: 'kosny-cedar-vj-127x18',
    name: 'Western Red Cedar V-joint 127×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 127,
    coverWidth: 127 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 41.50,
    supplier: 'Kosny',
    notes: 'Grade A · vee joint cladding',
  },

  // Panelling (Sauna Profile)
  {
    id: 'kosny-cedar-panel-84x10',
    name: 'Western Red Cedar Sauna Panelling 84×10mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 84,
    coverWidth: 84 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 19.40,
    supplier: 'Kosny',
    notes: 'Grade A · sauna profile panelling',
  },

  // Shiplap
  {
    id: 'kosny-cedar-ship-78x18',
    name: 'Western Red Cedar Shiplap 78×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 78,
    coverWidth: 78 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 27.80,
    supplier: 'Kosny',
    notes: 'Grade A · shiplap cladding',
  },
  {
    id: 'kosny-cedar-ship-127x18',
    name: 'Western Red Cedar Shiplap 127×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 127,
    coverWidth: 127 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 41.50,
    supplier: 'Kosny',
    notes: 'Grade A · shiplap cladding',
  },

  // Rough Sawn Charred Look
  {
    id: 'kosny-cedar-rscharred-120x18',
    name: 'Western Red Cedar Rough Sawn Charred 120×18mm',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 120,
    coverWidth: 120,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 38.30,
    supplier: 'Kosny',
    notes: 'Grade B (knotty) · rough sawn charred look',
  },

  // Castellated
  {
    id: 'kosny-cedar-cast-78x18-d1',
    name: 'Western Red Cedar Castellated 78×18mm — Decor 1',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 78,
    coverWidth: 78 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 33.40,
    supplier: 'Kosny',
    notes: 'Grade A · castellated, single groove (Decor 1)',
  },
  {
    id: 'kosny-cedar-cast-78x18-d2',
    name: 'Western Red Cedar Castellated 78×18mm — Decor 2',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 78,
    coverWidth: 78 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 33.40,
    supplier: 'Kosny',
    notes: 'Grade A · castellated, double groove (Decor 2)',
  },
  {
    id: 'kosny-cedar-cast-127x18-d3',
    name: 'Western Red Cedar Castellated 127×18mm — Decor 3',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 127,
    coverWidth: 127 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 50.00,
    supplier: 'Kosny',
    notes: 'Grade A · castellated, triple groove (Decor 3)',
  },
  {
    id: 'kosny-cedar-cast-78x26-d1',
    name: 'Western Red Cedar Castellated 78×26mm — Decor 1',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 78,
    coverWidth: 78 - KOSNY_TONGUE_MM,
    thickness: 26,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 49.40,
    supplier: 'Kosny',
    notes: 'Grade A · thick castellated, single groove (Decor 1)',
  },

  // Square dressed / pencil round — 12mm thickness → battens
  {
    id: 'kosny-cedar-sd-12x12',
    name: 'Western Red Cedar 12×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 12,
    coverWidth: 12,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 5.20,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-17x12',
    name: 'Western Red Cedar 17×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 17,
    coverWidth: 17,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 6.80,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-40x12',
    name: 'Western Red Cedar 40×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 40,
    coverWidth: 40,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 10.90,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-65x12',
    name: 'Western Red Cedar 65×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 65,
    coverWidth: 65,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 16.20,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-90x12',
    name: 'Western Red Cedar 90×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 21.65,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-115x12',
    name: 'Western Red Cedar 115×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 115,
    coverWidth: 115,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 28.30,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-140x12',
    name: 'Western Red Cedar 140×12mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 140,
    coverWidth: 140,
    thickness: 12,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 33.95,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },

  // 17mm thickness → battens (narrow) and backrest (wide)
  {
    id: 'kosny-cedar-sd-17x17',
    name: 'Western Red Cedar 17×17mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 17,
    coverWidth: 17,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 7.35,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-22x17',
    name: 'Western Red Cedar 22×17mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 22,
    coverWidth: 22,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 8.80,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-30x17',
    name: 'Western Red Cedar 30×17mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 30,
    coverWidth: 30,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 11.15,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-40x17',
    name: 'Western Red Cedar 40×17mm dressed',
    category: 'batten',
    species: 'Western Red Cedar',
    faceWidth: 40,
    coverWidth: 40,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 13.65,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-65x17',
    name: 'Western Red Cedar 65×17mm dressed',
    category: 'backrest',
    species: 'Western Red Cedar',
    faceWidth: 65,
    coverWidth: 65,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 20.40,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round · backrest-friendly width',
  },
  {
    id: 'kosny-cedar-sd-90x17',
    name: 'Western Red Cedar 90×17mm dressed',
    category: 'backrest',
    species: 'Western Red Cedar',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 27.20,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-115x17',
    name: 'Western Red Cedar 115×17mm dressed',
    category: 'backrest',
    species: 'Western Red Cedar',
    faceWidth: 115,
    coverWidth: 115,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 38.35,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-140x17',
    name: 'Western Red Cedar 140×17mm dressed',
    category: 'backrest',
    species: 'Western Red Cedar',
    faceWidth: 140,
    coverWidth: 140,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 42.70,
    supplier: 'Kosny',
    notes: 'Grade A · square dressed or pencil round',
  },
  {
    id: 'kosny-cedar-sd-190x17',
    name: 'Western Red Cedar 190×17mm dressed',
    category: 'wallCladding',
    species: 'Western Red Cedar',
    faceWidth: 190,
    coverWidth: 190,
    thickness: 17,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 61.35,
    supplier: 'Kosny',
    notes: 'Grade A · wide flat board, suitable as cladding or wide bench top',
  },

  // 38mm thickness → bench slats / framing
  {
    id: 'kosny-cedar-sd-30x38',
    name: 'Western Red Cedar 30×38mm dressed',
    category: 'framing',
    species: 'Western Red Cedar',
    faceWidth: 30,
    coverWidth: 30,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 20.60,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm structural section',
  },
  {
    id: 'kosny-cedar-sd-40x38',
    name: 'Western Red Cedar 40×38mm dressed',
    category: 'framing',
    species: 'Western Red Cedar',
    faceWidth: 40,
    coverWidth: 40,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 21.55,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm structural section',
  },
  {
    id: 'kosny-cedar-sd-65x38-slat',
    name: 'Western Red Cedar 65×38mm bench slat',
    category: 'benchSlat',
    species: 'Western Red Cedar',
    faceWidth: 65,
    coverWidth: 65,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 35.00,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm thick — bench slat / heavy fascia',
  },
  {
    id: 'kosny-cedar-sd-90x38-slat',
    name: 'Western Red Cedar 90×38mm bench slat',
    category: 'benchSlat',
    species: 'Western Red Cedar',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 53.15,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm thick · classic bench top width',
  },
  {
    id: 'kosny-cedar-sd-115x38-slat',
    name: 'Western Red Cedar 115×38mm bench slat',
    category: 'benchSlat',
    species: 'Western Red Cedar',
    faceWidth: 115,
    coverWidth: 115,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 74.95,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm thick',
  },
  {
    id: 'kosny-cedar-sd-140x38-slat',
    name: 'Western Red Cedar 140×38mm bench slat',
    category: 'benchSlat',
    species: 'Western Red Cedar',
    faceWidth: 140,
    coverWidth: 140,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 92.75,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm thick',
  },
  {
    id: 'kosny-cedar-sd-190x38-slat',
    name: 'Western Red Cedar 190×38mm bench top',
    category: 'benchSlat',
    species: 'Western Red Cedar',
    faceWidth: 190,
    coverWidth: 190,
    thickness: 38,
    stockLengths: KOSNY_CEDAR_LENGTHS,
    pricePerLM: 119.90,
    supplier: 'Kosny',
    notes: 'Grade A · 38mm thick wide bench top',
  },
];

const KOSNY_HINOKI_PROFILES: Profile[] = [
  // V-joint
  {
    id: 'kosny-hinoki-vj-86x10',
    name: 'Hinoki V-joint 86×10mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 12.90,
    supplier: 'Kosny',
    notes: 'Near clear · vee joint cladding',
  },
  {
    id: 'kosny-hinoki-vj-136x10',
    name: 'Hinoki V-joint 136×10mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · vee joint cladding',
  },
  {
    id: 'kosny-hinoki-vj-86x18',
    name: 'Hinoki V-joint 86×18mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · vee joint cladding',
  },
  {
    id: 'kosny-hinoki-vj-136x18',
    name: 'Hinoki V-joint 136×18mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 26.20,
    supplier: 'Kosny',
    notes: 'Near clear · vee joint cladding',
  },

  // Panelling
  {
    id: 'kosny-hinoki-panel-86x10',
    name: 'Hinoki Sauna Panelling 86×10mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 12.90,
    supplier: 'Kosny',
    notes: 'Near clear · sauna profile panelling',
  },

  // Shiplap
  {
    id: 'kosny-hinoki-ship-86x18',
    name: 'Hinoki Shiplap 86×18mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · shiplap cladding',
  },
  {
    id: 'kosny-hinoki-ship-136x18',
    name: 'Hinoki Shiplap 136×18mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 26.20,
    supplier: 'Kosny',
    notes: 'Near clear · shiplap cladding',
  },

  // Rough sawn charred
  {
    id: 'kosny-hinoki-rscharred-136x18',
    name: 'Hinoki Rough Sawn Charred 136×18mm',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 136,
    coverWidth: 136,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 26.20,
    supplier: 'Kosny',
    notes: 'Near clear · rough sawn charred look',
  },

  // Castellated
  {
    id: 'kosny-hinoki-cast-86x18-d1',
    name: 'Hinoki Castellated 86×18mm — Decor 1',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · castellated, single groove',
  },
  {
    id: 'kosny-hinoki-cast-86x18-d2',
    name: 'Hinoki Castellated 86×18mm — Decor 2',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · castellated, double groove',
  },
  {
    id: 'kosny-hinoki-cast-136x18-d3',
    name: 'Hinoki Castellated 136×18mm — Decor 3',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 26.20,
    supplier: 'Kosny',
    notes: 'Near clear · castellated, triple groove',
  },
  {
    id: 'kosny-hinoki-cast-90x32-d1',
    name: 'Hinoki Castellated 90×32mm — Decor 1',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 90,
    coverWidth: 90 - KOSNY_TONGUE_MM,
    thickness: 32,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 23.50,
    supplier: 'Kosny',
    notes: 'Near clear · thick castellated, single groove',
  },
  {
    id: 'kosny-hinoki-cast-140x32-d3',
    name: 'Hinoki Castellated 140×32mm — Decor 3',
    category: 'wallCladding',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 140,
    coverWidth: 140 - KOSNY_TONGUE_MM,
    thickness: 32,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 34.20,
    supplier: 'Kosny',
    notes: 'Near clear · thick castellated, triple groove',
  },

  // Pencil round
  {
    id: 'kosny-hinoki-dpr-42x42',
    name: 'Hinoki 42×42mm DPR',
    category: 'framing',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 42,
    coverWidth: 42,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round',
  },
  {
    id: 'kosny-hinoki-dpr-42x18',
    name: 'Hinoki 42×18mm DPR',
    category: 'benchSlat',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 42,
    coverWidth: 42,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 10.25,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round',
  },
  {
    id: 'kosny-hinoki-dpr-86x18',
    name: 'Hinoki 86×18mm DPR',
    category: 'benchSlat',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 86,
    coverWidth: 86,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 18.20,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round',
  },
  {
    id: 'kosny-hinoki-dpr-136x18',
    name: 'Hinoki 136×18mm DPR',
    category: 'benchSlat',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 136,
    coverWidth: 136,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 26.20,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round',
  },
  {
    id: 'kosny-hinoki-dpr-90x42',
    name: 'Hinoki 90×42mm DPR',
    category: 'framing',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 34.20,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round · framing-grade thickness',
  },
  {
    id: 'kosny-hinoki-dpr-140x42',
    name: 'Hinoki 140×42mm DPR',
    category: 'framing',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 140,
    coverWidth: 140,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 53.00,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round',
  },
  {
    id: 'kosny-hinoki-dpr-190x42',
    name: 'Hinoki 190×42mm DPR',
    category: 'framing',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 190,
    coverWidth: 190,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 68.40,
    supplier: 'Kosny',
    notes: 'Near clear · double pencil round',
  },

  // Rough sawn (structural)
  {
    id: 'kosny-hinoki-rs-48x150',
    name: 'Hinoki Rough Sawn 48×150mm',
    category: 'framing',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 48,
    coverWidth: 48,
    thickness: 150,
    stockLengths: [2.8, 3.0, 3.8, 4.0],
    pricePerLM: 52.80,
    supplier: 'Kosny',
    notes: 'Near clear · structural rough sawn',
  },
  {
    id: 'kosny-hinoki-rs-48x200',
    name: 'Hinoki Rough Sawn 48×200mm',
    category: 'framing',
    species: 'Hinoki (Japanese cypress)',
    faceWidth: 48,
    coverWidth: 48,
    thickness: 200,
    stockLengths: [2.8, 3.0, 3.8, 4.0],
    pricePerLM: 70.50,
    supplier: 'Kosny',
    notes: 'Near clear · structural rough sawn',
  },
];

const KOSNY_SUGI_PROFILES: Profile[] = [
  // V-joint
  {
    id: 'kosny-sugi-vj-86x10',
    name: 'Sugi V-joint 86×10mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 11.10,
    supplier: 'Kosny',
    notes: 'Tight knots · vee joint cladding',
  },
  {
    id: 'kosny-sugi-vj-136x10',
    name: 'Sugi V-joint 136×10mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.60,
    supplier: 'Kosny',
    notes: 'Tight knots · vee joint cladding',
  },
  {
    id: 'kosny-sugi-vj-86x18',
    name: 'Sugi V-joint 86×18mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.50,
    supplier: 'Kosny',
    notes: 'Tight knots · vee joint cladding',
  },
  {
    id: 'kosny-sugi-vj-136x18',
    name: 'Sugi V-joint 136×18mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 22.25,
    supplier: 'Kosny',
    notes: 'Tight knots · vee joint cladding',
  },

  // Panelling
  {
    id: 'kosny-sugi-panel-86x10',
    name: 'Sugi Sauna Panelling 86×10mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 10,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 11.10,
    supplier: 'Kosny',
    notes: 'Tight knots · sauna profile panelling',
  },

  // Shiplap
  {
    id: 'kosny-sugi-ship-86x18',
    name: 'Sugi Shiplap 86×18mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.50,
    supplier: 'Kosny',
    notes: 'Tight knots · shiplap cladding',
  },
  {
    id: 'kosny-sugi-ship-136x18',
    name: 'Sugi Shiplap 136×18mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 22.25,
    supplier: 'Kosny',
    notes: 'Tight knots · shiplap cladding',
  },

  // Rough sawn charred
  {
    id: 'kosny-sugi-rscharred-136x18',
    name: 'Sugi Rough Sawn Charred 136×18mm',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 136,
    coverWidth: 136,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 22.25,
    supplier: 'Kosny',
    notes: 'Tight knots · rough sawn charred look',
  },

  // Castellated
  {
    id: 'kosny-sugi-cast-86x18-d1',
    name: 'Sugi Castellated 86×18mm — Decor 1',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.50,
    supplier: 'Kosny',
    notes: 'Tight knots · castellated, single groove',
  },
  {
    id: 'kosny-sugi-cast-86x18-d2',
    name: 'Sugi Castellated 86×18mm — Decor 2',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.50,
    supplier: 'Kosny',
    notes: 'Tight knots · castellated, double groove',
  },
  {
    id: 'kosny-sugi-cast-136x18-d3',
    name: 'Sugi Castellated 136×18mm — Decor 3',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 136,
    coverWidth: 136 - KOSNY_TONGUE_MM,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 22.25,
    supplier: 'Kosny',
    notes: 'Tight knots · castellated, triple groove',
  },
  {
    id: 'kosny-sugi-cast-90x32-d1',
    name: 'Sugi Castellated 90×32mm — Decor 1',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 90,
    coverWidth: 90 - KOSNY_TONGUE_MM,
    thickness: 32,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 19.95,
    supplier: 'Kosny',
    notes: 'Tight knots · thick castellated, single groove',
  },
  {
    id: 'kosny-sugi-cast-140x32-d3',
    name: 'Sugi Castellated 140×32mm — Decor 3',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 140,
    coverWidth: 140 - KOSNY_TONGUE_MM,
    thickness: 32,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 28.95,
    supplier: 'Kosny',
    notes: 'Tight knots · thick castellated, triple groove',
  },

  // Pencil round
  {
    id: 'kosny-sugi-dpr-42x42',
    name: 'Sugi 42×42mm DPR',
    category: 'framing',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 42,
    coverWidth: 42,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.50,
    supplier: 'Kosny',
    notes: 'Tight knots · double pencil round',
  },
  {
    id: 'kosny-sugi-dpr-42x18',
    name: 'Sugi 42×18mm DPR',
    category: 'benchSlat',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 42,
    coverWidth: 42,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 8.95,
    supplier: 'Kosny',
    notes: 'Tight knots · double pencil round',
  },
  {
    id: 'kosny-sugi-dpr-86x18',
    name: 'Sugi 86×18mm DPR',
    category: 'benchSlat',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 86,
    coverWidth: 86,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 15.50,
    supplier: 'Kosny',
    notes: 'Tight knots · double pencil round',
  },
  {
    id: 'kosny-sugi-dpr-136x18',
    name: 'Sugi 136×18mm DPR',
    category: 'benchSlat',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 136,
    coverWidth: 136,
    thickness: 18,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 22.25,
    supplier: 'Kosny',
    notes: 'Tight knots · double pencil round',
  },
  {
    id: 'kosny-sugi-dpr-90x42',
    name: 'Sugi 90×42mm DPR',
    category: 'framing',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 90,
    coverWidth: 90,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 28.75,
    supplier: 'Kosny',
    notes: 'Tight knots · double pencil round · framing-grade thickness',
  },
  {
    id: 'kosny-sugi-dpr-140x42',
    name: 'Sugi 140×42mm DPR',
    category: 'framing',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 140,
    coverWidth: 140,
    thickness: 42,
    stockLengths: KOSNY_JAPANESE_LENGTHS,
    pricePerLM: 42.25,
    supplier: 'Kosny',
    notes: 'Tight knots · double pencil round',
  },

  // Rough sawn
  {
    id: 'kosny-sugi-rs-50x150',
    name: 'Sugi Rough Sawn 50×150mm',
    category: 'framing',
    species: 'Sugi (Japanese cedar)',
    faceWidth: 50,
    coverWidth: 50,
    thickness: 150,
    stockLengths: [3.0, 4.0],
    pricePerLM: 36.30,
    supplier: 'Kosny',
    notes: 'Tight knots · structural rough sawn',
  },

  // Yakisugi
  {
    id: 'kosny-sugi-yakisugi-165x18-raw',
    name: 'Yakisugi (charred & brushed) 165×18mm — Raw',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar) · Yakisugi',
    faceWidth: 165,
    coverWidth: 165,
    thickness: 18,
    stockLengths: [3.9],
    pricePerLM: 24.60,
    supplier: 'Kosny',
    notes: 'Charred & brushed · uncoated',
  },
  {
    id: 'kosny-sugi-yakisugi-165x18-woca',
    name: 'Yakisugi (charred & brushed) 165×18mm — Coated WOCA',
    category: 'wallCladding',
    species: 'Sugi (Japanese cedar) · Yakisugi',
    faceWidth: 165,
    coverWidth: 165,
    thickness: 18,
    stockLengths: [3.9],
    pricePerLM: 27.90,
    supplier: 'Kosny',
    notes: 'Charred & brushed · WOCA coated',
  },
];

// ───────────────────────────────────────────────────────────────────────────
// Combined export
// ───────────────────────────────────────────────────────────────────────────

export const SEED_PROFILES: Profile[] = [
  ...ORIGINAL_PROFILES,
  ...SDS_AUSTRALIA_PROFILES,
  ...SDS_CEDAR_PROFILES,
  ...KOSNY_CEDAR_PROFILES,
  ...KOSNY_HINOKI_PROFILES,
  ...KOSNY_SUGI_PROFILES,
];

export const SEED_MATERIALS: MaterialItem[] = [
  {
    id: 'rockwool-rwa45-75',
    name: 'Rockwool RWA45 75mm',
    category: 'insulation',
    unit: 'm2',
    unitSize: 4.32,
    pricePerUnit: null,
    supplier: 'Rockwool',
    notes: 'Stone wool batts (1.2 × 0.6 × 0.075m), 4 batts per pack',
  },
  {
    id: 'rockwool-rwa45-100',
    name: 'Rockwool RWA45 100mm',
    category: 'insulation',
    unit: 'm2',
    unitSize: 3.6,
    pricePerUnit: null,
    supplier: 'Rockwool',
    notes: '',
  },
  {
    id: 'sauna-foil-paper',
    name: 'Sauna foil paper backed',
    category: 'vapourBarrier',
    unit: 'roll',
    unitSize: 30,
    pricePerUnit: null,
    supplier: 'Modinex',
    notes: '1.2m × 25m roll',
  },
  {
    id: 'sauna-pure-foil',
    name: 'Sauna pure aluminium foil',
    category: 'vapourBarrier',
    unit: 'roll',
    unitSize: 30,
    pricePerUnit: null,
    supplier: 'Modinex',
    notes: '1.2m × 25m roll',
  },
  {
    id: 'sds-foil-reflector',
    name: 'SDS Authentic Aluminium Foil / Reflector',
    category: 'vapourBarrier',
    unit: 'roll',
    unitSize: 30,
    pricePerUnit: 154.00,
    supplier: 'SDS Australia',
    notes: 'SKU FOIL-REF · paper-backed aluminium · inc-GST',
  },
  {
    id: 'foil-tape-50',
    name: 'Aluminium foil tape 50mm',
    category: 'tape',
    unit: 'roll',
    unitSize: 50,
    pricePerUnit: null,
    supplier: 'Modinex',
    notes: '50mm × 50m',
  },
  {
    id: 'sds-ametalin-tape-48',
    name: 'Ametalin Insulation/Ducting Tape 48mm × 50m',
    category: 'tape',
    unit: 'roll',
    unitSize: 50,
    pricePerUnit: 33.00,
    supplier: 'SDS Australia',
    notes: 'SKU Ametalin-48-50 · seal foil joins · inc-GST',
  },
  {
    id: 'ss-cladding-nail',
    name: 'SS 4×40 ribbed cladding nail',
    category: 'fixings',
    unit: 'box',
    unitSize: 500,
    pricePerUnit: null,
    supplier: 'Local fastener supplier',
    notes: 'per box of 500',
  },
  {
    id: 'ss-bench-screw',
    name: 'SS 5×60 bench screw',
    category: 'fixings',
    unit: 'box',
    unitSize: 250,
    pricePerUnit: null,
    supplier: 'Local fastener supplier',
    notes: 'per box of 250',
  },
];

export const SEED_LIBRARY: Library = {
  profiles: SEED_PROFILES,
  materials: SEED_MATERIALS,
};

/**
 * Default selections — match the SDS Australia quote (Q-003752) sent for the
 * Slow Folk Brunswick build. Users can swap any of these in the Profiles tab
 * after opening the app; insulation/screws stay generic since the quote
 * doesn't include those line items.
 */
export const DEFAULT_PROFILE_SELECTIONS = {
  wallCladding: 'sds-alder-ht-90x15-tg',
  ceilingCladding: 'sds-alder-ht-90x15-tg',
  benchSlat: 'sds-alder-ht-90x21-slat',
  benchFraming: 'sds-euro-framing-90x35',
  batten: 'sds-euro-framing-70x19-batten',
  backrest: 'sds-alder-ht-65x21-fascia',
  insulation: 'rockwool-rwa45-75',
  ceilingInsulation: 'rockwool-rwa45-100',
  vapourBarrier: 'sds-foil-reflector',
  tape: 'sds-ametalin-tape-48',
  claddingScrews: 'ss-cladding-nail',
  benchScrews: 'ss-bench-screw',
} as const;

/** Reference selections used by the unit-test fixture — pinned for snapshot stability. */
export const THERMO_ASPEN_REFERENCE_SELECTIONS = {
  wallCladding: 'thermo-aspen-116-tg',
  ceilingCladding: 'thermo-aspen-116-tg',
  benchSlat: 'abachi-90-slat',
  benchFraming: 'pine-42x42-framing',
  batten: 'pine-22x42-batten',
  backrest: 'thermo-aspen-backrest',
  insulation: 'rockwool-rwa45-75',
  ceilingInsulation: 'rockwool-rwa45-100',
  vapourBarrier: 'sauna-foil-paper',
  tape: 'foil-tape-50',
  claddingScrews: 'ss-cladding-nail',
  benchScrews: 'ss-bench-screw',
} as const;
