import type { Project } from '@/types/saunaMaterials';
import { THERMO_ASPEN_REFERENCE_SELECTIONS } from '@/lib/saunaMaterials/seedLibrary';

export const SLOW_FOLK_PROJECT: Project = {
  id: 'slow-folk-brunswick',
  name: 'Slow Folk Brunswick',
  client: 'Slow Folk',
  location: '219 Albion Street Brunswick VIC',
  createdAt: '2026-05-05T00:00:00.000Z',
  updatedAt: '2026-05-05T00:00:00.000Z',
  room: {
    length: 5518,
    width: 3830,
    ceilingHeight: 2400,
  },
  openings: [
    {
      id: 'door-west',
      type: 'door',
      wall: 'west',
      shape: 'rectangle',
      width: 920,
      height: 2375,
    },
    {
      id: 'window-south',
      type: 'window',
      wall: 'south',
      shape: 'circle',
      width: 1530,
      height: 1530,
    },
  ],
  heaterZone: {
    wall: 'south',
    width: 1500,
    height: 2400,
    finish: 'tile',
  },
  columns: [
    {
      id: 'column-south',
      wall: 'south',
      width: 290,
      depth: 290,
      height: 2400,
      finish: 'tile',
      extendsToCeiling: true,
    },
  ],
  benches: [
    {
      id: 'climb-step-north',
      tier: 'climbStep',
      wall: 'north',
      length: 3771,
      depth: 300,
      topHeight: 300,
      hasBackrest: false,
      backrestHeight: 0,
      hasEndCap: 'none',
      closedFront: true,
    },
    {
      id: 'foot-bench-north',
      tier: 'foot',
      wall: 'north',
      length: 3771,
      depth: 600,
      topHeight: 750,
      hasBackrest: false,
      backrestHeight: 0,
      hasEndCap: 'right',
      closedFront: true,
    },
    {
      id: 'upper-bench-north',
      tier: 'upper',
      wall: 'north',
      length: 3771,
      depth: 600,
      topHeight: 1200,
      hasBackrest: true,
      backrestHeight: 250,
      hasEndCap: 'right',
      closedFront: true,
    },
    {
      id: 'accessible-bench-east',
      tier: 'accessible',
      wall: 'east',
      length: 5266,
      depth: 600,
      topHeight: 450,
      hasBackrest: false,
      backrestHeight: 0,
      hasEndCap: 'left',
      closedFront: true,
    },
  ],
  construction: {
    behindBenchClad: true,
    crossBattening: false,
    battenSpacing: 600,
    insulationDepth: 90,
    vapourBarrierType: 'foilPaper',
    ceilingInsulationDepth: 140,
    fixingsDensityCladding: 20,
    fixingsDensityBench: 8,
  },
  waste: {
    cladding: 0.12,
    benchSlat: 0.08,
    framing: 0.10,
    batten: 0.10,
  },
  profiles: { ...THERMO_ASPEN_REFERENCE_SELECTIONS },
};
